config/routes.rb
Rails.application.routes.draw do
  root to: 'questions#index'

  resources :users, except: %i[index], param: :nickname

  resource :session, only: %i[new create destroy]

  resources :questions do
    put "hide", on: :member
  end

  resources :hashtags, only: %i[show], param: :name
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/hashtag.rb
class Hashtag < ApplicationRecord
  PATTERN = /#[\p{Word}-]+/i
  has_many :hashtag_questions, dependent: :destroy
  has_many :questions, through: :hashtag_questions

  before_validation :downcase_name

  validates :name, presence: true, uniqueness: true, length: { maximum: 255 }

  private

  def downcase_name
    name.downcase!
  end
end

app/models/hashtag_question.rb
class HashtagQuestion < ApplicationRecord
  belongs_to :question
  belongs_to :hashtag

  validates :question, uniqueness: { scope: :hashtag_id }
end

app/models/question.rb
class Question < ApplicationRecord
  validates :body, presence: true, length: { maximum: 280 }
  belongs_to :user
  belongs_to :author, class_name: "User", optional: true
  has_many :hashtag_questions, dependent: :destroy
  has_many :hashtags, through: :hashtag_questions
  after_save_commit :create_hashtags

  def hidden?
    hidden == true
  end

  private

  def create_hashtags
    Hashtags::HashtagCreator.call(self)
  end
end

app/models/user.rb
class User < ApplicationRecord
  include Gravtastic
  gravtastic(secure: true, filetype: :png, size: 100, default: 'retro')

  validates :email, presence: true, uniqueness: true, length: { maximum: 40 }, format: { with: /\A\w+@\w+\.[A-Za-z]+\z/ }
  validates :nickname, presence: true, uniqueness: true, length: { maximum: 40 }, format: { with: /\A\w+\z/ }
  has_secure_password
  has_many :questions, dependent: :destroy
  has_many :asked_questions, dependent: :nullify, class_name: "Question"

  before_validation :downcase_nickname, :downcase_email

  private

  def downcase_nickname
    nickname&.downcase!
  end

  def downcase_email
    email&.downcase!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  private

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def redirect_with_alert
    redirect_to root_path, alert: 'Вам сюда нельзя!'
  end
end

app/controllers/hashtags_controller.rb
class HashtagsController < ApplicationController
  before_action :set_hashtag, only: %i[show]

  def show
    @questions = @hashtag.questions.includes(%i[author user hashtags])
  end

  private

  def set_hashtag
    @hashtag = Hashtag.find_by(name: params[:name])
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :ensure_current_user, only: %i[update destroy edit]
  before_action :set_question_for_current_user, only: %i[edit update destroy hide]
  before_action :set_question, only: %i[show]

  def create
    question_params = params.require(:question).permit(:body, :user_id)
    question_params[:author] = current_user
    @question = Question.new(question_params)

    if check_captcha(@question) && @question.save
      redirect_to user_path(@question.user.nickname), notice: "Новый вопрос создан!"
    else
      render :new
    end
  end

  def update
    question_params = params.require(:question).permit(:body, :answer)
    @question.update(question_params)

    redirect_to question_path(@question), notice: "Вопрос обновлён!"
  end

  def destroy
    user = @question.user
    @question.destroy

    redirect_to user_path(user.nickname), notice: "Вопрос удалён!"
  end

  def index
    @hashtags = Hashtag.joins(:questions).distinct.order(created_at: :desc)
    @questions = Question.includes(%i[user author hashtags]).order(created_at: :desc).first(10)
    @users = User.order(created_at: :desc).first(10)
  end

  def new
    @user = User.find_by!(nickname: params[:user_nickname])
    @question = Question.new(user: @user)
  end

  def edit
  end

  def hide
    @question.update(hidden: true)
    redirect_to question_path(@question), notice: "Вопрос скрыт!"
  end

  private

  def set_question
    @question = Question.includes(:hashtags).find(params[:id])
  end

  def set_question_for_current_user
    @question = current_user.questions.find(params[:id])
  end

  def ensure_current_user
    redirect_with_alert unless current_user.present?
  end

  def check_captcha(model)
    current_user.present? || verify_recaptcha(model: model)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user_params = params.require(:session)
    user = User.find_by(email: user_params[:email])&.authenticate(user_params[:password])

    if user.present?
      session[:user_id] = user.id
      redirect_to root_path, notice: 'Вы вошли на сайт'
    else
      flash[:alert] = 'Неправильный email или пароль'
      render :new
    end
  end

  def new
  end

  def destroy
    session.delete(:user_id)

    redirect_to root_path, notice: 'Вы вышли из аккаунта'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[edit update destroy show]
  before_action :authorize_user, only: %i[edit update destroy]

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice: 'Вы успешно зарегистрировались'
    else
      flash.now[:alert] = 'Вы неправильно заполнили поля формы регистрации'
      render :new
    end
  end

  def new
    @user = User.new
  end

  def edit
    redirect_with_alert unless @user == current_user
  end

  def show
    @questions = @user.questions.includes(%i[hashtags author])
    @question = Question.new(user: @user)
  end

  def update
    if @user.update(user_params)
      redirect_to root_path, notice: 'Данные пользователя обновлены'
    else
      flash.now[:alert] = 'При попытке сохранить пользователя возникли ошибки'
      render :edit
    end
  end

  def destroy
    @user.destroy

    session.delete(:user_id)

    redirect_to root_path, notice: 'Пользователь удалён'
  end

  private

  def user_params
    params.require(:user).permit(:name, :nickname, :navbar_color, :email, :password, :password_confirmation)
  end

  def set_user
    @user = User.find_by!(nickname: params[:nickname])
  end

  def authorize_user
    redirect_with_alert unless @user == current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def inclination(count, one, few, many)
    return many if (count % 100).between?(10, 20)

    case count % 10
    when 1 then one
    when 2..4 then few
    else
      many
    end
  end
end

app/helpers/hashtags_helper.rb
module HashtagsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def question_link(question)
    link_to "Вопрос #{question.id}", question_path(question)
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_helper.rb
module UserHelper
  def nickname_output(user)
    "@#{user.nickname}"
  end

  def navbar_color_style(user)
    "background-color: #{user.navbar_color}"
  end
end

app/views/hashtags/_hashtag.html.erb
<%= link_to "##{hashtag.name}", hashtag_path(hashtag.name) %>

app/views/hashtags/show.html.erb
<div class="container mt">
  <h2 class="title-lg mb-md">
    Вопросы #<%= @hashtag.name %>
  </h2>
  <% @questions.each do |question|%>
    <div class="mb-lg">
      <h2 class="title-sm mb"><%= question_link question %></h2>
      <%= render question %>
      <span class="text-bold">Теги:</span>
      <%= render question.hashtags %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Askme</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="wrapper">
      <div class="navbar" style="<%= navbar_color_style(current_user) if current_user.present? %>">
        <p class="title-sm text-bold"><%= link_to "Ask me!", root_path %></p>
        <div>
          <% if current_user.present? %>
            <%= link_to nickname_output(current_user), user_path(current_user.nickname), class: 'mr-sm' %>
            <%= button_to "Выйти", session_path, method: :delete %>
          <% else %>
            <%= link_to "Регистрация", new_user_path, class: 'button button-yellow mr-sm' %>
            <%= link_to "Вход", new_session_path, class: 'button button-yellow' %>
          <% end %>
        </div>
      </div>
      <% if flash[:notice].present? %>
        <p class="mb mt message message-notice"><%= flash[:notice] %></p>
      <% elsif flash[:alert].present? %>
        <p class="mb mt message message-alert"><%= flash[:alert] %></p>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/questions/_form.html.erb
<%= form_with model: question, data: { turbo: false }, class: "mb-lg" do |form| %>
  <p><%= form.label :body, 'Текст вопроса' %></p>
  <p><%= form.text_area :body, rows: 5, class: 'form-text-area' %></p>

  <p><%= form.hidden_field :user_id, class: 'form-text-field' %></p>

  <% if question.persisted? %>
    <p class="mt"><%= form.label :answer, 'Ответ' %></p>
    <p><%= form.text_area :answer, rows: 5, class: 'form-text-area' %></p>
  <% end %>

  <%= recaptcha_tags unless current_user.present? %>

  <p class="mt"><%= form.submit 'Сохранить', class: 'button button-main' %> или <%= link_to "вернуться", :back %></p>
<% end %>

app/views/questions/_question.html.erb
<div class="mb-sm">
  <div class="mb-md text-bold">
    <% if question.author.nil? %>
      Анонимно
    <% elsif question.author == current_user %>
      Вы задали
    <% else %>
      От <%= link_to nickname_output(question.author), user_path(question.author.nickname) %>
    <% end %>
    <% if question.user == current_user %>
      вам:
    <% else %>
      пользователю <%= link_to nickname_output(question.user), user_path(question.user.nickname) %>:
    <% end %>
  </div>

  <div class="mb-sm">
    <%= simple_format(html_escape(question.body)) %>
  </div>

  <div class="text-sm question-footer">
    <div class="text-grey">
      <%= l(question.created_at, format: :short) %>
    </div>

    <% if question.user == current_user %>
      <div>
        <% edit_icon = question.answer.blank? ? 'reply' : 'pencil' %>
        <%= link_to fa_icon(edit_icon), edit_question_path(question), title: 'Изменить вопрос' %>
        <%= button_to fa_icon('trash-o'), question_path(question), method: :delete, title: 'Удалить вопрос', form: { data: { turbo_confirm: 'Удалить вопрос?'}} %>
        <% unless question.hidden? %>
          <%= button_to fa_icon('eye-slash'), hide_question_path(question), method: :put, title: 'Скрыть вопрос', form: { data: { turbo_confirm: 'Скрыть вопрос?'}} %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/questions/_tags.html.erb
<% hashtags.each do |hashtag| %>
  <%= hashtag_link(hashtag) unless hashtag.questions? %>
<% end %>

app/views/questions/edit.html.erb
<div class="container">
  <h2 class="title-lg mb">Редактирование вопроса <%= @question.id %></h2>

  <%= render "form", question: @question %>
</div>

app/views/questions/hashtag.html.erb
<div class="container mt">
  <h2 class="title-lg mb-md">
      Вопросы <%= hashtag_link(@hashtag) %>
  </h2>
  <% @questions.each do |question|%>
    <div class="mb-lg">
      <h2 class="title-sm mb"><%= question_link question %></h2>
      <%= render question %>
      <% unless question.hashtags.empty? %>
        <span class="text-bold">Теги:</span>
        <%= render "questions/hashtags", hashtags: question.hashtags%>
      <% end %>
    </div>
  <% end %>
</div>

app/views/questions/index.html.erb
<div class="container">
  <h2 class="title-lg mb">
    Недавно добавились
  </h2>

  <div class="users-box">
    <% @users.each do |user| %>
      <%= render "users/user_avatar", user: user %>
    <% end %>
  </div>
</div>

<div class="container mt">
  <h2 class="title-lg mb-md">Все теги</h2>
  <%= render @hashtags %>
</div>

<div class="container mt">
  <h2 class="title-lg mb-md">
    <%= inclination(@questions.count, 'Последний', 'Последние', 'Последние') %>
    <%= @questions.count %>
    <%= inclination(@questions.count, 'вопрос', 'вопроса', 'вопросов') %>
  </h2>
  <% @questions.each do |question| %>
    <div class="mb-lg">
      <h2 class="title-sm mb"><%= question_link question %></h2>
      <%= render question %>
      <span class="text-bold">Теги:</span>
      <%= render question.hashtags %>
    </div>
  <% end %>
</div>

app/views/questions/new.html.erb
<div class="container">
  <h2 class="title-lg mb">Новый вопрос</h2>
  <p class="mb">для <%= link_to "@#{@question.user.nickname}", user_path(@question.user.nickname) %></p>

  <% if @question.errors.any? %>
    <div class="mt">
      <% @question.errors.full_messages.each do |message| %>
        <p class="mb-sm text-red"><%= message %></p>
      <% end %>
    </div>
  <% end %>

  <%= render "form", question: @question %>
</div>

app/views/questions/show.html.erb
<div class="container">
  <h2 class="title-lg mb">Вопрос <%= @question.id %></h2>

  <div class="mb-sm">
    <%= render "question", question: @question %>
  </div>

  <div class="text-bold">Ответ:</div>
  <% if @question.answer.present? %>
    <div class="mb-sm text-dark-red">
      <%= @question.answer %>
    </div>
  <% else %>
    <div class="mb-sm text-grey">отсутсвует</div>
  <% end %>
  <span class="text-bold">Теги:</span>
  <%= render @question.hashtags %>

  <div class="mt"><%= link_to "Все вопросы", questions_path %></div>
</div>

app/views/users/_empty_state.html.erb
<div class="mt-md mb-md empty-state">
  <p class="mb-sm title-md text-grey">Этому пользователю ещё никто не задал вопрос</p>
  <%= link_to "Задайте вопрос первым", new_question_path(user_nickname: user.nickname) %>
</div>

app/views/users/_user_avatar.html.erb
<% background_class = "users-box-user-bg#{user.id % 5}" %>

<div class="users-box-user <%= background_class %> rounded mr ml mb">
  <a href="<%= user_path(user.nickname) %>" class="mb-sm">
    <%= image_tag user.gravatar_url, title: nickname_output(user), class: "rounded" %>
  </a>
</div>

app/views/users/edit.html.erb
<div class="container">
  <h2 class="title">Редактирование профиля</h2>

  <% if @user.errors.any? %>
    <div class="mt">
      <% @user.errors.full_messages.each do |message| %>
        <p class="mb-sm text-red"><%= message %></p>
      <% end %>
    </div>
  <% end %>

  <div class="mt">
    <%= form_with model: @user, url: user_path(@user.nickname), method: :patch, data: {turbo: false} do |form| %>
      <p><%= image_tag @user.gravatar_url, title: "@#{@user.nickname}", class: 'rounded' %></p>
      <p class="text-sm">Чтобы добавить или поменять аватар — зарегистрируйтесь на <%= link_to "Gravatar", 'https://gravatar.com' %> и загрузите фото</p>

      <p><%= form.label :name, 'Имя' %></p>
      <p><%= form.text_field :name, class: 'form-text-field' %></p>

      <p class="mt"><%= form.label :nickname, 'Ник на сайте' %></p>
      <p><%= form.text_field :nickname, class: 'form-text-field' %></p>

      <p class="mt"><%= form.label :navbar_color, 'Цвет фона навигационной панели' %></p>
      <p><%= form.color_field :navbar_color %></p>

      <p class="mt-lg text-sm">Если не хотите менять пароль — оставьте эти поля пустыми!</p>

      <p class="mt"><%= form.label :password, 'Пароль' %></p>
      <p><%= form.password_field :password, class: 'form-text-field' %></p>

      <p class="mt"><%= form.label :password_confirmation, 'Подтверждение пароля' %></p>
      <p><%= form.password_field :password_confirmation, class: 'form-text-field' %></p>

      <p class="mt-lg">
        <%= form.submit "Сохранить", class: 'button button-main' %>
        <span class="text-sm">или <%= link_to "вернуться", :back %></span>
      </p>
    <% end %>
  </div>

  <div class="mt-lg">
    <%= button_to "Удалить профиль", user_path(@user.nickname),
      method: :delete,
      form: {data: {turbo_confirm: "Вы точно хотите удалить свой профиль?"}},
      class: 'text-red text-sm' %>
  </div>
</div>

app/views/users/new.html.erb
<div class="container">
  <h2 class="title">Присоединяйся и спрашивай!</h2>

  <% if @user.errors.any? %>
    <div class="mt">
      <% @user.errors.full_messages.each do |message| %>
        <p class="mb-sm text-red"><%= message %></p>
      <% end %>
    </div>
  <% end %>

  <div class="mt">
    <%= form_with model: @user, data: { turbo: false } do |form| %>
      <p><%= form.label :name, 'Ваше имя' %></p>
      <p><%= form.text_field :name, class: 'form-text-field' %></p>

      <p class="mt"><%= form.label :nickname, 'Ник на сайте' %></p>
      <p><%= form.text_field :nickname, class: 'form-text-field' %></p>

      <p class="mt"><%= form.label :email %></p>
      <p><%= form.text_field :email, class: 'form-text-field' %></p>

      <p class="mt"><%= form.label :password, 'Пароль' %></p>
      <p><%= form.password_field :password, class: 'form-text-field' %></p>

      <p class="mt"><%= form.label :password_confirmation, 'Пароль ещё раз' %></p>
      <p><%= form.password_field :password_confirmation, class: 'form-text-field' %></p>

      <p><%= form.submit "Зарегистрироваться", class: 'button button-main mt-lg' %></p>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="user-box mb-sm">
  <h2 class="title-lg mt-lg"><%= @user.name %></h2>

  <div class="mt">
    <%= render "users/user_avatar", user: @user %>
  </div>
  <p class="text-bold mt mb-lg">@<%= @user.nickname %></p>
  <% if current_user == @user %>
    <p class="mt mb-lg">
      <%= link_to fa_icon('pencil'), edit_user_path(@user.nickname) %>
    </p>
  <% end %>
</div>

<%= link_to 'Спроси меня', new_question_path(user_nickname: @user.nickname), class: 'button button-yellow' %>

<% if @questions.any? %>
  <div class="container mt-sm">
    <h2 class="title-lg">
      <%= @questions.count %>
      <%= inclination(@questions.count, 'вопрос', 'вопроса', 'вопросов') %>
    </h2>
  </div>

  <% @questions.each do |question| %>
    <div class="mt-sm container">
      <h2 class="title-sm mb"><%= question_link question %></h2>
      <%= render question %>
      <span class="text-bold">Теги:</span>
      <%= render question.hashtags %>
    </div>
  <% end %>
<% else %>
  <%= render "users/empty_state", user: @user %>
<% end %>